# Generated by Django 4.1 on 2024-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_unit_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
