# Generated by Django 4.1 on 2024-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_unit_date_created_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
