# Generated by Django 4.1 on 2024-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_unit_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
