# Generated by Django 4.1 on 2024-09-19 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_unit_date_created_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
