# Generated by Django 4.1 on 2024-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='random_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
