# Generated by Django 4.1 on 2024-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_business_email_user_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_id',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
