# Generated by Django 4.1 on 2024-09-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='units',
        ),
        migrations.AddField(
            model_name='business',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit'),
        ),
    ]
