# Generated by Django 4.1 on 2024-09-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_business_units_business_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_no',
        ),
    ]
