# Generated by Django 4.1 on 2024-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_business_logo_remove_business_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspend_message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
