# Generated by Django 4.1 on 2024-09-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_user_suspend_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
