# Generated by Django 4.1 on 2024-10-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_business_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='unit',
        ),
    ]
