# Generated by Django 4.1 on 2024-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
