# Generated by Django 4.1 on 2024-10-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_business_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socials',
            old_name='linkedin',
            new_name='linkedln',
        ),
    ]
