# Generated by Django 4.1 on 2024-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_rename_linkedin_socials_linkedln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimages',
            name='image',
            field=models.ImageField(upload_to='business_images'),
        ),
    ]
